services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#    ports: ['192.168.10.89:8000:8000'] # To run on a specific ip
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=docker_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    depends_on:
      - db